// Code generated by protoc-gen-go. DO NOT EDIT.
// source: catalog.proto

/*
Package catalog is a generated protocol buffer package.

It is generated from these files:
	catalog.proto

It has these top-level messages:
	DetailRequest
	DetailResponse
	AllCategoriesRequest
	AllCategoriesResponse
	CategoryProductsRequest
	CategoryProductsResponse
	SearchRequest
	SearchResponse
	Product
	ProductCategory
	Error
*/
package catalog

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ErrorCode int32

const (
	ErrorCode_UNKNOWN          ErrorCode = 0
	ErrorCode_NOSUCHSKU        ErrorCode = 1
	ErrorCode_NOSUCHCATEGORY   ErrorCode = 2
	ErrorCode_NOTAUTHORIZED    ErrorCode = 3
	ErrorCode_BADSEARCHREQUEST ErrorCode = 4
)

var ErrorCode_name = map[int32]string{
	0: "UNKNOWN",
	1: "NOSUCHSKU",
	2: "NOSUCHCATEGORY",
	3: "NOTAUTHORIZED",
	4: "BADSEARCHREQUEST",
}
var ErrorCode_value = map[string]int32{
	"UNKNOWN":          0,
	"NOSUCHSKU":        1,
	"NOSUCHCATEGORY":   2,
	"NOTAUTHORIZED":    3,
	"BADSEARCHREQUEST": 4,
}

func (x ErrorCode) String() string {
	return proto.EnumName(ErrorCode_name, int32(x))
}
func (ErrorCode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type DetailRequest struct {
	SKU string `protobuf:"bytes,1,opt,name=SKU" json:"SKU,omitempty"`
}

func (m *DetailRequest) Reset()                    { *m = DetailRequest{} }
func (m *DetailRequest) String() string            { return proto.CompactTextString(m) }
func (*DetailRequest) ProtoMessage()               {}
func (*DetailRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DetailRequest) GetSKU() string {
	if m != nil {
		return m.SKU
	}
	return ""
}

type DetailResponse struct {
	Product *Product `protobuf:"bytes,1,opt,name=Product" json:"Product,omitempty"`
	Error   *Error   `protobuf:"bytes,100,opt,name=Error" json:"Error,omitempty"`
}

func (m *DetailResponse) Reset()                    { *m = DetailResponse{} }
func (m *DetailResponse) String() string            { return proto.CompactTextString(m) }
func (*DetailResponse) ProtoMessage()               {}
func (*DetailResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DetailResponse) GetProduct() *Product {
	if m != nil {
		return m.Product
	}
	return nil
}

func (m *DetailResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type AllCategoriesRequest struct {
	Unused int32 `protobuf:"varint,1,opt,name=Unused" json:"Unused,omitempty"`
}

func (m *AllCategoriesRequest) Reset()                    { *m = AllCategoriesRequest{} }
func (m *AllCategoriesRequest) String() string            { return proto.CompactTextString(m) }
func (*AllCategoriesRequest) ProtoMessage()               {}
func (*AllCategoriesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AllCategoriesRequest) GetUnused() int32 {
	if m != nil {
		return m.Unused
	}
	return 0
}

type AllCategoriesResponse struct {
	Categories []*ProductCategory `protobuf:"bytes,1,rep,name=Categories" json:"Categories,omitempty"`
	Error      *Error             `protobuf:"bytes,100,opt,name=Error" json:"Error,omitempty"`
}

func (m *AllCategoriesResponse) Reset()                    { *m = AllCategoriesResponse{} }
func (m *AllCategoriesResponse) String() string            { return proto.CompactTextString(m) }
func (*AllCategoriesResponse) ProtoMessage()               {}
func (*AllCategoriesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *AllCategoriesResponse) GetCategories() []*ProductCategory {
	if m != nil {
		return m.Categories
	}
	return nil
}

func (m *AllCategoriesResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type CategoryProductsRequest struct {
	CategoryID uint64 `protobuf:"varint,1,opt,name=CategoryID" json:"CategoryID,omitempty"`
}

func (m *CategoryProductsRequest) Reset()                    { *m = CategoryProductsRequest{} }
func (m *CategoryProductsRequest) String() string            { return proto.CompactTextString(m) }
func (*CategoryProductsRequest) ProtoMessage()               {}
func (*CategoryProductsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CategoryProductsRequest) GetCategoryID() uint64 {
	if m != nil {
		return m.CategoryID
	}
	return 0
}

type CategoryProductsResponse struct {
	Products []*Product `protobuf:"bytes,1,rep,name=Products" json:"Products,omitempty"`
	Error    *Error     `protobuf:"bytes,100,opt,name=Error" json:"Error,omitempty"`
}

func (m *CategoryProductsResponse) Reset()                    { *m = CategoryProductsResponse{} }
func (m *CategoryProductsResponse) String() string            { return proto.CompactTextString(m) }
func (*CategoryProductsResponse) ProtoMessage()               {}
func (*CategoryProductsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *CategoryProductsResponse) GetProducts() []*Product {
	if m != nil {
		return m.Products
	}
	return nil
}

func (m *CategoryProductsResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type SearchRequest struct {
	SearchTerm string   `protobuf:"bytes,1,opt,name=SearchTerm" json:"SearchTerm,omitempty"`
	Categories []uint64 `protobuf:"varint,2,rep,packed,name=Categories" json:"Categories,omitempty"`
}

func (m *SearchRequest) Reset()                    { *m = SearchRequest{} }
func (m *SearchRequest) String() string            { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()               {}
func (*SearchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *SearchRequest) GetSearchTerm() string {
	if m != nil {
		return m.SearchTerm
	}
	return ""
}

func (m *SearchRequest) GetCategories() []uint64 {
	if m != nil {
		return m.Categories
	}
	return nil
}

type SearchResponse struct {
	SearchResults []*Product `protobuf:"bytes,1,rep,name=SearchResults" json:"SearchResults,omitempty"`
	Error         *Error     `protobuf:"bytes,100,opt,name=Error" json:"Error,omitempty"`
}

func (m *SearchResponse) Reset()                    { *m = SearchResponse{} }
func (m *SearchResponse) String() string            { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()               {}
func (*SearchResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *SearchResponse) GetSearchResults() []*Product {
	if m != nil {
		return m.SearchResults
	}
	return nil
}

func (m *SearchResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

type Product struct {
	SKU          string `protobuf:"bytes,1,opt,name=SKU" json:"SKU,omitempty"`
	Name         string `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	Description  string `protobuf:"bytes,3,opt,name=Description" json:"Description,omitempty"`
	Manufacturer string `protobuf:"bytes,4,opt,name=Manufacturer" json:"Manufacturer,omitempty"`
	Model        string `protobuf:"bytes,5,opt,name=Model" json:"Model,omitempty"`
	Price        int64  `protobuf:"varint,6,opt,name=Price" json:"Price,omitempty"`
}

func (m *Product) Reset()                    { *m = Product{} }
func (m *Product) String() string            { return proto.CompactTextString(m) }
func (*Product) ProtoMessage()               {}
func (*Product) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Product) GetSKU() string {
	if m != nil {
		return m.SKU
	}
	return ""
}

func (m *Product) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Product) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Product) GetManufacturer() string {
	if m != nil {
		return m.Manufacturer
	}
	return ""
}

func (m *Product) GetModel() string {
	if m != nil {
		return m.Model
	}
	return ""
}

func (m *Product) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

type ProductCategory struct {
	CategoryID  uint64 `protobuf:"varint,1,opt,name=CategoryID" json:"CategoryID,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=Name" json:"Name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=Description" json:"Description,omitempty"`
}

func (m *ProductCategory) Reset()                    { *m = ProductCategory{} }
func (m *ProductCategory) String() string            { return proto.CompactTextString(m) }
func (*ProductCategory) ProtoMessage()               {}
func (*ProductCategory) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *ProductCategory) GetCategoryID() uint64 {
	if m != nil {
		return m.CategoryID
	}
	return 0
}

func (m *ProductCategory) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ProductCategory) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type Error struct {
	Code     ErrorCode `protobuf:"varint,1,opt,name=Code,enum=catalog.ErrorCode" json:"Code,omitempty"`
	HttpHint uint32    `protobuf:"varint,2,opt,name=HttpHint" json:"HttpHint,omitempty"`
	Message  string    `protobuf:"bytes,3,opt,name=Message" json:"Message,omitempty"`
}

func (m *Error) Reset()                    { *m = Error{} }
func (m *Error) String() string            { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()               {}
func (*Error) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *Error) GetCode() ErrorCode {
	if m != nil {
		return m.Code
	}
	return ErrorCode_UNKNOWN
}

func (m *Error) GetHttpHint() uint32 {
	if m != nil {
		return m.HttpHint
	}
	return 0
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func init() {
	proto.RegisterType((*DetailRequest)(nil), "catalog.DetailRequest")
	proto.RegisterType((*DetailResponse)(nil), "catalog.DetailResponse")
	proto.RegisterType((*AllCategoriesRequest)(nil), "catalog.AllCategoriesRequest")
	proto.RegisterType((*AllCategoriesResponse)(nil), "catalog.AllCategoriesResponse")
	proto.RegisterType((*CategoryProductsRequest)(nil), "catalog.CategoryProductsRequest")
	proto.RegisterType((*CategoryProductsResponse)(nil), "catalog.CategoryProductsResponse")
	proto.RegisterType((*SearchRequest)(nil), "catalog.SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "catalog.SearchResponse")
	proto.RegisterType((*Product)(nil), "catalog.Product")
	proto.RegisterType((*ProductCategory)(nil), "catalog.ProductCategory")
	proto.RegisterType((*Error)(nil), "catalog.Error")
	proto.RegisterEnum("catalog.ErrorCode", ErrorCode_name, ErrorCode_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Catalog service

type CatalogClient interface {
	GetProductDetails(ctx context.Context, in *DetailRequest, opts ...client.CallOption) (*DetailResponse, error)
	GetProductCategories(ctx context.Context, in *AllCategoriesRequest, opts ...client.CallOption) (*AllCategoriesResponse, error)
	GetProductsInCategory(ctx context.Context, in *CategoryProductsRequest, opts ...client.CallOption) (*CategoryProductsResponse, error)
	ProductSearch(ctx context.Context, in *SearchRequest, opts ...client.CallOption) (*SearchResponse, error)
}

type catalogClient struct {
	c           client.Client
	serviceName string
}

func NewCatalogClient(serviceName string, c client.Client) CatalogClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "catalog"
	}
	return &catalogClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *catalogClient) GetProductDetails(ctx context.Context, in *DetailRequest, opts ...client.CallOption) (*DetailResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Catalog.GetProductDetails", in)
	out := new(DetailResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) GetProductCategories(ctx context.Context, in *AllCategoriesRequest, opts ...client.CallOption) (*AllCategoriesResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Catalog.GetProductCategories", in)
	out := new(AllCategoriesResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) GetProductsInCategory(ctx context.Context, in *CategoryProductsRequest, opts ...client.CallOption) (*CategoryProductsResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Catalog.GetProductsInCategory", in)
	out := new(CategoryProductsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) ProductSearch(ctx context.Context, in *SearchRequest, opts ...client.CallOption) (*SearchResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Catalog.ProductSearch", in)
	out := new(SearchResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Catalog service

type CatalogHandler interface {
	GetProductDetails(context.Context, *DetailRequest, *DetailResponse) error
	GetProductCategories(context.Context, *AllCategoriesRequest, *AllCategoriesResponse) error
	GetProductsInCategory(context.Context, *CategoryProductsRequest, *CategoryProductsResponse) error
	ProductSearch(context.Context, *SearchRequest, *SearchResponse) error
}

func RegisterCatalogHandler(s server.Server, hdlr CatalogHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Catalog{hdlr}, opts...))
}

type Catalog struct {
	CatalogHandler
}

func (h *Catalog) GetProductDetails(ctx context.Context, in *DetailRequest, out *DetailResponse) error {
	return h.CatalogHandler.GetProductDetails(ctx, in, out)
}

func (h *Catalog) GetProductCategories(ctx context.Context, in *AllCategoriesRequest, out *AllCategoriesResponse) error {
	return h.CatalogHandler.GetProductCategories(ctx, in, out)
}

func (h *Catalog) GetProductsInCategory(ctx context.Context, in *CategoryProductsRequest, out *CategoryProductsResponse) error {
	return h.CatalogHandler.GetProductsInCategory(ctx, in, out)
}

func (h *Catalog) ProductSearch(ctx context.Context, in *SearchRequest, out *SearchResponse) error {
	return h.CatalogHandler.ProductSearch(ctx, in, out)
}

func init() { proto.RegisterFile("catalog.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 603 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x5d, 0x6f, 0x94, 0x40,
	0x14, 0x75, 0xbf, 0xba, 0xed, 0x5d, 0x59, 0xe9, 0x64, 0xdb, 0x92, 0x4d, 0x6c, 0x28, 0x31, 0xa6,
	0x69, 0x4c, 0x1f, 0xd6, 0xc4, 0xe8, 0x9b, 0x2b, 0x90, 0x6e, 0xd3, 0x14, 0xea, 0xb0, 0xc4, 0x68,
	0x7c, 0xa1, 0x30, 0xae, 0x24, 0x14, 0xd6, 0x99, 0x21, 0xa6, 0x3f, 0xc7, 0x3f, 0xe3, 0xef, 0x32,
	0x3b, 0x0c, 0x2c, 0x74, 0x6d, 0x6d, 0x7c, 0xe3, 0x9e, 0x7b, 0xe6, 0xcc, 0xb9, 0x97, 0x3b, 0x17,
	0x94, 0x30, 0xe0, 0x41, 0x92, 0x2d, 0x4e, 0x97, 0x34, 0xe3, 0x19, 0xea, 0xcb, 0xd0, 0x38, 0x02,
	0xc5, 0x22, 0x3c, 0x88, 0x13, 0x4c, 0x7e, 0xe4, 0x84, 0x71, 0xa4, 0x42, 0xc7, 0xbb, 0xf0, 0xb5,
	0x96, 0xde, 0x3a, 0xde, 0xc1, 0xab, 0x4f, 0xe3, 0x1a, 0x86, 0x25, 0x85, 0x2d, 0xb3, 0x94, 0x11,
	0x74, 0x02, 0xfd, 0x2b, 0x9a, 0x45, 0x79, 0xc8, 0x05, 0x6f, 0x30, 0x51, 0x4f, 0x4b, 0x79, 0x89,
	0xe3, 0x92, 0x80, 0x5e, 0x40, 0xcf, 0xa6, 0x34, 0xa3, 0x5a, 0x24, 0x98, 0xc3, 0x8a, 0x29, 0x50,
	0x5c, 0x24, 0x8d, 0x53, 0x18, 0x4d, 0x93, 0xc4, 0x0c, 0x38, 0x59, 0x64, 0x34, 0x26, 0xac, 0x74,
	0xb3, 0x0f, 0x5b, 0x7e, 0x9a, 0x33, 0x12, 0x89, 0x8b, 0x7a, 0x58, 0x46, 0xc6, 0x4f, 0xd8, 0xbb,
	0xc3, 0x97, 0xd6, 0xde, 0x02, 0xac, 0x51, 0xad, 0xa5, 0x77, 0x8e, 0x07, 0x13, 0xed, 0xae, 0x3b,
	0xc9, 0xb8, 0xc5, 0x35, 0xee, 0x23, 0x8d, 0xbe, 0x83, 0x83, 0xf2, 0xb4, 0x14, 0xab, 0xbc, 0x1e,
	0x56, 0x57, 0xdf, 0x9e, 0x5b, 0xc2, 0x6f, 0x17, 0xd7, 0x10, 0x23, 0x05, 0x6d, 0xf3, 0xa8, 0xb4,
	0xfd, 0x0a, 0xb6, 0x4b, 0x4c, 0x9a, 0xde, 0x6c, 0x69, 0xc5, 0x78, 0xa4, 0x55, 0x17, 0x14, 0x8f,
	0x04, 0x34, 0xfc, 0x5e, 0x33, 0x58, 0x00, 0x73, 0x42, 0x6f, 0xe4, 0x1f, 0xae, 0x21, 0xb5, 0x02,
	0x56, 0xbd, 0x6b, 0xeb, 0x9d, 0x5a, 0x01, 0x31, 0x61, 0x46, 0x0a, 0xc3, 0x52, 0x50, 0xda, 0x7e,
	0xb3, 0xbe, 0x82, 0xe5, 0xc9, 0x03, 0xde, 0x9b, 0xb4, 0x47, 0x16, 0xf0, 0xab, 0x55, 0xcd, 0xd9,
	0xe6, 0x58, 0x22, 0x04, 0x5d, 0x27, 0xb8, 0x21, 0x5a, 0x5b, 0x40, 0xe2, 0x1b, 0xe9, 0x30, 0xb0,
	0x08, 0x0b, 0x69, 0xbc, 0xe4, 0x71, 0x96, 0x6a, 0x1d, 0x91, 0xaa, 0x43, 0xc8, 0x80, 0xa7, 0x97,
	0x41, 0x9a, 0x7f, 0x0b, 0x42, 0x9e, 0x53, 0x42, 0xb5, 0xae, 0xa0, 0x34, 0x30, 0x34, 0x82, 0xde,
	0x65, 0x16, 0x91, 0x44, 0xeb, 0x89, 0x64, 0x11, 0xac, 0xd0, 0x2b, 0x1a, 0x87, 0x44, 0xdb, 0xd2,
	0x5b, 0xc7, 0x1d, 0x5c, 0x04, 0xc6, 0x02, 0x9e, 0xdd, 0x19, 0xaa, 0x7f, 0xcd, 0xc1, 0xff, 0x19,
	0x37, 0x88, 0x6c, 0x19, 0x7a, 0x09, 0x5d, 0x33, 0x8b, 0x88, 0x10, 0x1e, 0x4e, 0x50, 0xb3, 0x75,
	0xab, 0x0c, 0x16, 0x79, 0x34, 0x86, 0xed, 0x19, 0xe7, 0xcb, 0x59, 0x9c, 0x72, 0x71, 0x95, 0x82,
	0xab, 0x18, 0x69, 0xd0, 0xbf, 0x24, 0x8c, 0x05, 0x0b, 0x22, 0xaf, 0x2a, 0xc3, 0x93, 0x08, 0x76,
	0x2a, 0x21, 0x34, 0x80, 0xbe, 0xef, 0x5c, 0x38, 0xee, 0x27, 0x47, 0x7d, 0x82, 0x14, 0xd8, 0x71,
	0x5c, 0xcf, 0x37, 0x67, 0xde, 0x85, 0xaf, 0xb6, 0x10, 0x82, 0x61, 0x11, 0x9a, 0xd3, 0xb9, 0x7d,
	0xe6, 0xe2, 0xcf, 0x6a, 0x1b, 0xed, 0x82, 0xe2, 0xb8, 0xf3, 0xa9, 0x3f, 0x9f, 0xb9, 0xf8, 0xfc,
	0x8b, 0x6d, 0xa9, 0x1d, 0x34, 0x02, 0xf5, 0xc3, 0xd4, 0xf2, 0xec, 0x29, 0x36, 0x67, 0xd8, 0xfe,
	0xe8, 0xdb, 0xde, 0x5c, 0xed, 0x4e, 0x7e, 0xb7, 0xa1, 0x6f, 0x16, 0xbe, 0x91, 0x05, 0xbb, 0x67,
	0x84, 0xcb, 0x26, 0x16, 0x8b, 0x86, 0xa1, 0xfd, 0xaa, 0xac, 0xc6, 0x76, 0x1a, 0x1f, 0x6c, 0xe0,
	0x72, 0x12, 0x7d, 0x18, 0xad, 0x55, 0x6a, 0xaf, 0xfa, 0x79, 0x75, 0xe0, 0x6f, 0xfb, 0x65, 0x7c,
	0x78, 0x5f, 0x5a, 0xca, 0x7e, 0x85, 0xbd, 0xb5, 0x2c, 0x3b, 0x4f, 0xab, 0x9f, 0xac, 0x57, 0x07,
	0xef, 0x59, 0x07, 0xe3, 0xa3, 0x07, 0x18, 0x52, 0xfd, 0x3d, 0x28, 0x12, 0x2b, 0x9e, 0x47, 0xad,
	0xec, 0xc6, 0xcb, 0xad, 0x95, 0xdd, 0x7c, 0x80, 0xd7, 0x5b, 0x62, 0x9d, 0xbf, 0xfe, 0x13, 0x00,
	0x00, 0xff, 0xff, 0xb5, 0xa7, 0x52, 0xd7, 0xdf, 0x05, 0x00, 0x00,
}
