// Code generated by protoc-gen-go. DO NOT EDIT.
// source: warehouse.proto

/*
Package warehouse is a generated protocol buffer package.

It is generated from these files:
	warehouse.proto

It has these top-level messages:
	DetailsRequest
	DetailsResponse
*/
package warehouse

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DetailsRequest struct {
	SKU string `protobuf:"bytes,1,opt,name=SKU" json:"SKU,omitempty"`
}

func (m *DetailsRequest) Reset()                    { *m = DetailsRequest{} }
func (m *DetailsRequest) String() string            { return proto.CompactTextString(m) }
func (*DetailsRequest) ProtoMessage()               {}
func (*DetailsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DetailsRequest) GetSKU() string {
	if m != nil {
		return m.SKU
	}
	return ""
}

type DetailsResponse struct {
	SKU            string `protobuf:"bytes,1,opt,name=SKU" json:"SKU,omitempty"`
	StockRemaining uint32 `protobuf:"varint,2,opt,name=StockRemaining" json:"StockRemaining,omitempty"`
	Manufacturer   string `protobuf:"bytes,3,opt,name=Manufacturer" json:"Manufacturer,omitempty"`
	ModelNumber    string `protobuf:"bytes,4,opt,name=ModelNumber" json:"ModelNumber,omitempty"`
}

func (m *DetailsResponse) Reset()                    { *m = DetailsResponse{} }
func (m *DetailsResponse) String() string            { return proto.CompactTextString(m) }
func (*DetailsResponse) ProtoMessage()               {}
func (*DetailsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DetailsResponse) GetSKU() string {
	if m != nil {
		return m.SKU
	}
	return ""
}

func (m *DetailsResponse) GetStockRemaining() uint32 {
	if m != nil {
		return m.StockRemaining
	}
	return 0
}

func (m *DetailsResponse) GetManufacturer() string {
	if m != nil {
		return m.Manufacturer
	}
	return ""
}

func (m *DetailsResponse) GetModelNumber() string {
	if m != nil {
		return m.ModelNumber
	}
	return ""
}

func init() {
	proto.RegisterType((*DetailsRequest)(nil), "warehouse.DetailsRequest")
	proto.RegisterType((*DetailsResponse)(nil), "warehouse.DetailsResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Warehouse service

type WarehouseClient interface {
	GetWarehouseDetails(ctx context.Context, in *DetailsRequest, opts ...client.CallOption) (*DetailsResponse, error)
}

type warehouseClient struct {
	c           client.Client
	serviceName string
}

func NewWarehouseClient(serviceName string, c client.Client) WarehouseClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "warehouse"
	}
	return &warehouseClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *warehouseClient) GetWarehouseDetails(ctx context.Context, in *DetailsRequest, opts ...client.CallOption) (*DetailsResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Warehouse.GetWarehouseDetails", in)
	out := new(DetailsResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Warehouse service

type WarehouseHandler interface {
	GetWarehouseDetails(context.Context, *DetailsRequest, *DetailsResponse) error
}

func RegisterWarehouseHandler(s server.Server, hdlr WarehouseHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Warehouse{hdlr}, opts...))
}

type Warehouse struct {
	WarehouseHandler
}

func (h *Warehouse) GetWarehouseDetails(ctx context.Context, in *DetailsRequest, out *DetailsResponse) error {
	return h.WarehouseHandler.GetWarehouseDetails(ctx, in, out)
}

func init() { proto.RegisterFile("warehouse.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 202 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x4f, 0x2c, 0x4a,
	0xcd, 0xc8, 0x2f, 0x2d, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x84, 0x0b, 0x28,
	0x29, 0x71, 0xf1, 0xb9, 0xa4, 0x96, 0x24, 0x66, 0xe6, 0x14, 0x07, 0xa5, 0x16, 0x96, 0xa6, 0x16,
	0x97, 0x08, 0x09, 0x70, 0x31, 0x07, 0x7b, 0x87, 0x4a, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x81,
	0x98, 0x4a, 0x13, 0x19, 0xb9, 0xf8, 0xe1, 0x8a, 0x8a, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x31, 0x55,
	0x09, 0xa9, 0x71, 0xf1, 0x05, 0x97, 0xe4, 0x27, 0x67, 0x07, 0xa5, 0xe6, 0x26, 0x66, 0xe6, 0x65,
	0xe6, 0xa5, 0x4b, 0x30, 0x29, 0x30, 0x6a, 0xf0, 0x06, 0xa1, 0x89, 0x0a, 0x29, 0x71, 0xf1, 0xf8,
	0x26, 0xe6, 0x95, 0xa6, 0x25, 0x26, 0x97, 0x94, 0x16, 0xa5, 0x16, 0x49, 0x30, 0x83, 0x8d, 0x40,
	0x11, 0x13, 0x52, 0xe0, 0xe2, 0xf6, 0xcd, 0x4f, 0x49, 0xcd, 0xf1, 0x2b, 0xcd, 0x4d, 0x4a, 0x2d,
	0x92, 0x60, 0x01, 0x2b, 0x41, 0x16, 0x32, 0x8a, 0xe4, 0xe2, 0x0c, 0x87, 0x79, 0x42, 0xc8, 0x87,
	0x4b, 0xd8, 0x3d, 0xb5, 0x04, 0xce, 0x87, 0xba, 0x55, 0x48, 0x52, 0x0f, 0xe1, 0x71, 0x54, 0x4f,
	0x4a, 0x49, 0x61, 0x93, 0x82, 0x78, 0x2d, 0x89, 0x0d, 0x1c, 0x48, 0xc6, 0x80, 0x00, 0x00, 0x00,
	0xff, 0xff, 0x6c, 0x1f, 0x74, 0xd1, 0x37, 0x01, 0x00, 0x00,
}
