// Code generated by protoc-gen-go. DO NOT EDIT.
// source: shipping.proto

/*
Package shipping is a generated protocol buffer package.

It is generated from these files:
	shipping.proto

It has these top-level messages:
	ShippingCostRequest
	ShippingCostResponse
	MarkShippedRequest
	MarkShippedResponse
	ShippingStatusRequest
	ShippingStatusResponse
	ShippingCost
*/
package shipping

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
	context "golang.org/x/net/context"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ShippingMethod int32

const (
	ShippingMethod_UNKNOWN ShippingMethod = 0
	ShippingMethod_USPS    ShippingMethod = 1
	ShippingMethod_UPS     ShippingMethod = 2
	ShippingMethod_FEDEX   ShippingMethod = 3
	ShippingMethod_RAVEN   ShippingMethod = 4
)

var ShippingMethod_name = map[int32]string{
	0: "UNKNOWN",
	1: "USPS",
	2: "UPS",
	3: "FEDEX",
	4: "RAVEN",
}
var ShippingMethod_value = map[string]int32{
	"UNKNOWN": 0,
	"USPS":    1,
	"UPS":     2,
	"FEDEX":   3,
	"RAVEN":   4,
}

func (x ShippingMethod) String() string {
	return proto.EnumName(ShippingMethod_name, int32(x))
}
func (ShippingMethod) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ShippingCostRequest struct {
	SKU     string `protobuf:"bytes,1,opt,name=SKU" json:"SKU,omitempty"`
	Zipcode string `protobuf:"bytes,2,opt,name=Zipcode" json:"Zipcode,omitempty"`
}

func (m *ShippingCostRequest) Reset()                    { *m = ShippingCostRequest{} }
func (m *ShippingCostRequest) String() string            { return proto.CompactTextString(m) }
func (*ShippingCostRequest) ProtoMessage()               {}
func (*ShippingCostRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ShippingCostRequest) GetSKU() string {
	if m != nil {
		return m.SKU
	}
	return ""
}

func (m *ShippingCostRequest) GetZipcode() string {
	if m != nil {
		return m.Zipcode
	}
	return ""
}

type ShippingCostResponse struct {
	ShippingCosts []*ShippingCost `protobuf:"bytes,1,rep,name=ShippingCosts" json:"ShippingCosts,omitempty"`
}

func (m *ShippingCostResponse) Reset()                    { *m = ShippingCostResponse{} }
func (m *ShippingCostResponse) String() string            { return proto.CompactTextString(m) }
func (*ShippingCostResponse) ProtoMessage()               {}
func (*ShippingCostResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ShippingCostResponse) GetShippingCosts() []*ShippingCost {
	if m != nil {
		return m.ShippingCosts
	}
	return nil
}

type MarkShippedRequest struct {
	SKU            string         `protobuf:"bytes,1,opt,name=SKU" json:"SKU,omitempty"`
	OrderID        uint64         `protobuf:"varint,2,opt,name=OrderID" json:"OrderID,omitempty"`
	Note           string         `protobuf:"bytes,3,opt,name=Note" json:"Note,omitempty"`
	ShippingMethod ShippingMethod `protobuf:"varint,4,opt,name=ShippingMethod,enum=shipping.ShippingMethod" json:"ShippingMethod,omitempty"`
}

func (m *MarkShippedRequest) Reset()                    { *m = MarkShippedRequest{} }
func (m *MarkShippedRequest) String() string            { return proto.CompactTextString(m) }
func (*MarkShippedRequest) ProtoMessage()               {}
func (*MarkShippedRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *MarkShippedRequest) GetSKU() string {
	if m != nil {
		return m.SKU
	}
	return ""
}

func (m *MarkShippedRequest) GetOrderID() uint64 {
	if m != nil {
		return m.OrderID
	}
	return 0
}

func (m *MarkShippedRequest) GetNote() string {
	if m != nil {
		return m.Note
	}
	return ""
}

func (m *MarkShippedRequest) GetShippingMethod() ShippingMethod {
	if m != nil {
		return m.ShippingMethod
	}
	return ShippingMethod_UNKNOWN
}

type MarkShippedResponse struct {
	Success        bool   `protobuf:"varint,1,opt,name=Success" json:"Success,omitempty"`
	TrackingNumber string `protobuf:"bytes,2,opt,name=TrackingNumber" json:"TrackingNumber,omitempty"`
}

func (m *MarkShippedResponse) Reset()                    { *m = MarkShippedResponse{} }
func (m *MarkShippedResponse) String() string            { return proto.CompactTextString(m) }
func (*MarkShippedResponse) ProtoMessage()               {}
func (*MarkShippedResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *MarkShippedResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *MarkShippedResponse) GetTrackingNumber() string {
	if m != nil {
		return m.TrackingNumber
	}
	return ""
}

type ShippingStatusRequest struct {
	OrderID uint64 `protobuf:"varint,1,opt,name=OrderID" json:"OrderID,omitempty"`
}

func (m *ShippingStatusRequest) Reset()                    { *m = ShippingStatusRequest{} }
func (m *ShippingStatusRequest) String() string            { return proto.CompactTextString(m) }
func (*ShippingStatusRequest) ProtoMessage()               {}
func (*ShippingStatusRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ShippingStatusRequest) GetOrderID() uint64 {
	if m != nil {
		return m.OrderID
	}
	return 0
}

type ShippingStatusResponse struct {
	TrackingNumber string         `protobuf:"bytes,1,opt,name=TrackingNumber" json:"TrackingNumber,omitempty"`
	ShippingMethod ShippingMethod `protobuf:"varint,2,opt,name=ShippingMethod,enum=shipping.ShippingMethod" json:"ShippingMethod,omitempty"`
}

func (m *ShippingStatusResponse) Reset()                    { *m = ShippingStatusResponse{} }
func (m *ShippingStatusResponse) String() string            { return proto.CompactTextString(m) }
func (*ShippingStatusResponse) ProtoMessage()               {}
func (*ShippingStatusResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ShippingStatusResponse) GetTrackingNumber() string {
	if m != nil {
		return m.TrackingNumber
	}
	return ""
}

func (m *ShippingStatusResponse) GetShippingMethod() ShippingMethod {
	if m != nil {
		return m.ShippingMethod
	}
	return ShippingMethod_UNKNOWN
}

type ShippingCost struct {
	Method ShippingMethod `protobuf:"varint,1,opt,name=Method,enum=shipping.ShippingMethod" json:"Method,omitempty"`
	Price  int64          `protobuf:"varint,2,opt,name=Price" json:"Price,omitempty"`
}

func (m *ShippingCost) Reset()                    { *m = ShippingCost{} }
func (m *ShippingCost) String() string            { return proto.CompactTextString(m) }
func (*ShippingCost) ProtoMessage()               {}
func (*ShippingCost) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ShippingCost) GetMethod() ShippingMethod {
	if m != nil {
		return m.Method
	}
	return ShippingMethod_UNKNOWN
}

func (m *ShippingCost) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func init() {
	proto.RegisterType((*ShippingCostRequest)(nil), "shipping.ShippingCostRequest")
	proto.RegisterType((*ShippingCostResponse)(nil), "shipping.ShippingCostResponse")
	proto.RegisterType((*MarkShippedRequest)(nil), "shipping.MarkShippedRequest")
	proto.RegisterType((*MarkShippedResponse)(nil), "shipping.MarkShippedResponse")
	proto.RegisterType((*ShippingStatusRequest)(nil), "shipping.ShippingStatusRequest")
	proto.RegisterType((*ShippingStatusResponse)(nil), "shipping.ShippingStatusResponse")
	proto.RegisterType((*ShippingCost)(nil), "shipping.ShippingCost")
	proto.RegisterEnum("shipping.ShippingMethod", ShippingMethod_name, ShippingMethod_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for Shipping service

type ShippingClient interface {
	GetShippingCost(ctx context.Context, in *ShippingCostRequest, opts ...client.CallOption) (*ShippingCostResponse, error)
	MarkItemShipped(ctx context.Context, in *MarkShippedRequest, opts ...client.CallOption) (*MarkShippedResponse, error)
	GetShippingStatus(ctx context.Context, in *ShippingStatusRequest, opts ...client.CallOption) (*ShippingStatusResponse, error)
}

type shippingClient struct {
	c           client.Client
	serviceName string
}

func NewShippingClient(serviceName string, c client.Client) ShippingClient {
	if c == nil {
		c = client.NewClient()
	}
	if len(serviceName) == 0 {
		serviceName = "shipping"
	}
	return &shippingClient{
		c:           c,
		serviceName: serviceName,
	}
}

func (c *shippingClient) GetShippingCost(ctx context.Context, in *ShippingCostRequest, opts ...client.CallOption) (*ShippingCostResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Shipping.GetShippingCost", in)
	out := new(ShippingCostResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shippingClient) MarkItemShipped(ctx context.Context, in *MarkShippedRequest, opts ...client.CallOption) (*MarkShippedResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Shipping.MarkItemShipped", in)
	out := new(MarkShippedResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shippingClient) GetShippingStatus(ctx context.Context, in *ShippingStatusRequest, opts ...client.CallOption) (*ShippingStatusResponse, error) {
	req := c.c.NewRequest(c.serviceName, "Shipping.GetShippingStatus", in)
	out := new(ShippingStatusResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Shipping service

type ShippingHandler interface {
	GetShippingCost(context.Context, *ShippingCostRequest, *ShippingCostResponse) error
	MarkItemShipped(context.Context, *MarkShippedRequest, *MarkShippedResponse) error
	GetShippingStatus(context.Context, *ShippingStatusRequest, *ShippingStatusResponse) error
}

func RegisterShippingHandler(s server.Server, hdlr ShippingHandler, opts ...server.HandlerOption) {
	s.Handle(s.NewHandler(&Shipping{hdlr}, opts...))
}

type Shipping struct {
	ShippingHandler
}

func (h *Shipping) GetShippingCost(ctx context.Context, in *ShippingCostRequest, out *ShippingCostResponse) error {
	return h.ShippingHandler.GetShippingCost(ctx, in, out)
}

func (h *Shipping) MarkItemShipped(ctx context.Context, in *MarkShippedRequest, out *MarkShippedResponse) error {
	return h.ShippingHandler.MarkItemShipped(ctx, in, out)
}

func (h *Shipping) GetShippingStatus(ctx context.Context, in *ShippingStatusRequest, out *ShippingStatusResponse) error {
	return h.ShippingHandler.GetShippingStatus(ctx, in, out)
}

func init() { proto.RegisterFile("shipping.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 435 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xdd, 0x4e, 0xd4, 0x40,
	0x14, 0x76, 0xda, 0x42, 0xcb, 0x41, 0x4b, 0x3d, 0x20, 0x99, 0x6c, 0x44, 0x9b, 0x5e, 0x98, 0x8d,
	0x17, 0x44, 0xd7, 0x5b, 0x2f, 0x24, 0xb2, 0x18, 0x42, 0x28, 0x4d, 0x4b, 0x17, 0xe3, 0xdd, 0xd2,
	0x4e, 0xa0, 0x21, 0x6c, 0x6b, 0x67, 0xfa, 0x02, 0xc6, 0x67, 0xf0, 0x79, 0xcd, 0xb6, 0x33, 0xda,
	0x1f, 0xaa, 0xe1, 0xee, 0xfc, 0x7e, 0xe7, 0x3b, 0x67, 0xbe, 0x01, 0x9b, 0xdf, 0x66, 0x45, 0x91,
	0xad, 0x6e, 0x0e, 0x8b, 0x32, 0x17, 0x39, 0x5a, 0xca, 0xf7, 0x8e, 0x60, 0x37, 0x92, 0xf6, 0xe7,
	0x9c, 0x8b, 0x90, 0x7d, 0xaf, 0x18, 0x17, 0xe8, 0x80, 0x1e, 0x9d, 0xc5, 0x94, 0xb8, 0x64, 0xba,
	0x15, 0xae, 0x4d, 0xa4, 0x60, 0x7e, 0xcb, 0x8a, 0x24, 0x4f, 0x19, 0xd5, 0xea, 0xa8, 0x72, 0xbd,
	0x4b, 0xd8, 0xeb, 0x42, 0xf0, 0x22, 0x5f, 0x71, 0x86, 0x1f, 0xe1, 0x59, 0x3b, 0xce, 0x29, 0x71,
	0xf5, 0xe9, 0xf6, 0x6c, 0xff, 0xf0, 0x0f, 0x99, 0x4e, 0x5b, 0xb7, 0xd8, 0xfb, 0x45, 0x00, 0xcf,
	0x97, 0xe5, 0x5d, 0x1d, 0x65, 0xe9, 0x3f, 0x89, 0x5d, 0x94, 0x29, 0x2b, 0x4f, 0x8f, 0x6b, 0x62,
	0x46, 0xa8, 0x5c, 0x44, 0x30, 0xfc, 0x5c, 0x30, 0xaa, 0xd7, 0xc5, 0xb5, 0x8d, 0x9f, 0xc0, 0x56,
	0x73, 0xce, 0x99, 0xb8, 0xcd, 0x53, 0x6a, 0xb8, 0x64, 0x6a, 0xcf, 0xe8, 0x90, 0x55, 0x93, 0x0f,
	0x7b, 0xf5, 0xde, 0x15, 0xec, 0x76, 0x78, 0xc9, 0x6d, 0x29, 0x98, 0x51, 0x95, 0x24, 0x8c, 0xf3,
	0x9a, 0x9c, 0x15, 0x2a, 0x17, 0xdf, 0x80, 0x7d, 0x59, 0x2e, 0x93, 0xbb, 0x6c, 0x75, 0xe3, 0x57,
	0xf7, 0xd7, 0xac, 0x94, 0x07, 0xec, 0x45, 0xbd, 0xf7, 0xf0, 0x42, 0x8d, 0x8a, 0xc4, 0x52, 0x54,
	0x5c, 0xed, 0xdc, 0xda, 0x90, 0x74, 0x36, 0xf4, 0x7e, 0x10, 0xd8, 0xef, 0xf7, 0x48, 0x3e, 0xc3,
	0xa9, 0xe4, 0xa1, 0xa9, 0x0f, 0x1c, 0x44, 0x7b, 0xe4, 0x41, 0x16, 0xf0, 0xb4, 0xfd, 0x74, 0xf8,
	0x0e, 0x36, 0x25, 0x12, 0xf9, 0x0f, 0x92, 0xac, 0xc3, 0x3d, 0xd8, 0x08, 0xca, 0x2c, 0x69, 0x94,
	0xa5, 0x87, 0x8d, 0xf3, 0xf6, 0xa4, 0xcf, 0x0c, 0xb7, 0xc1, 0x8c, 0xfd, 0x33, 0xff, 0xe2, 0xca,
	0x77, 0x9e, 0xa0, 0x05, 0x46, 0x1c, 0x05, 0x91, 0x43, 0xd0, 0x04, 0x3d, 0x0e, 0x22, 0x47, 0xc3,
	0x2d, 0xd8, 0x38, 0x99, 0x1f, 0xcf, 0xbf, 0x3a, 0xfa, 0xda, 0x0c, 0x8f, 0x16, 0x73, 0xdf, 0x31,
	0x66, 0x3f, 0x35, 0xb0, 0x14, 0x10, 0x06, 0xb0, 0xf3, 0x85, 0x89, 0x0e, 0xdf, 0x83, 0x11, 0x41,
	0x36, 0xd7, 0x9f, 0xbc, 0x1a, 0x4b, 0xcb, 0x43, 0xfb, 0xb0, 0xb3, 0xd6, 0xc3, 0xa9, 0x60, 0xf7,
	0x52, 0x13, 0xf8, 0xf2, 0x6f, 0xcb, 0x50, 0xc2, 0x93, 0x83, 0x91, 0xac, 0xc4, 0x5b, 0xc0, 0xf3,
	0x16, 0xc3, 0xe6, 0x55, 0xf1, 0xf5, 0x90, 0x44, 0x47, 0x23, 0x13, 0x77, 0xbc, 0xa0, 0xc1, 0xbd,
	0xde, 0xac, 0xbf, 0xfe, 0x87, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x18, 0x95, 0x43, 0x13, 0x0c,
	0x04, 0x00, 0x00,
}
